// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtSOsEg5VgXtzXzo43SjjTMgSPcfE_rKc',
    appId: '1:402780514965:web:3b6c035ee6fde7a4a1499c',
    messagingSenderId: '402780514965',
    projectId: 'emergency-b114e',
    authDomain: 'emergency-b114e.firebaseapp.com',
    storageBucket: 'emergency-b114e.appspot.com',
    measurementId: 'G-HWVT2RX8VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAc8xjPhip2GcWegH7Ga3vwgZ9l1edPfM',
    appId: '1:402780514965:android:4db175209a3c025aa1499c',
    messagingSenderId: '402780514965',
    projectId: 'emergency-b114e',
    storageBucket: 'emergency-b114e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDm34zd-a38EwQXKQt5zZF0BHPzGszDc',
    appId: '1:402780514965:ios:cbaec618b1879f34a1499c',
    messagingSenderId: '402780514965',
    projectId: 'emergency-b114e',
    storageBucket: 'emergency-b114e.appspot.com',
    iosClientId: '402780514965-1ndljo69avnk9fknu1mm1suga5v0ntf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergency',
  );
}
